// @ts-nocheck
// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
import {numberWithUnitTokens} from "./calculus-number-with-unit-tokens.ts"
import {identifierTokens} from "./calculus-identifier-tokens.ts"
import {calculusLangHighlight} from "./calculus-lang-highlighting"
const spec_Identifier = {__proto__:null,IN:82, in:82, into:82, as:82, to:82}
export const parser = LRParser.deserialize({
  version: 14,
  states: "*[OVQYOOOOQW'#Cz'#CzOVQYO'#DROtQYO'#CdO!YQ[O'#CwO#VQ[O'#DUO#rQ]O'#CpOOQW'#Cp'#CpOOQW'#DU'#DUO#|QYO'#DUO$bQSO'#CyOOQW'#DT'#DTO%RQYO'#CaQOQQOOO%]QQO'#DROOQW-E6x-E6xO%eQQO,59mO%mQ[O,59OO!nQ[O'#DUOtQYO,59OOtQYO,59QOtQYO,59SOOQP'#Ck'#CkO&RQRO,59UOOQW,59c,59cO&WQSO,59cO&]QYO,59WOtQYO,58|OOQW,59],59]OOQW,59_,59_O&dQYO,59pO&uQYO'#DUO'^QZO'#CpOOQW,59e,59eOOQW'#C|'#C|O'hQYO,58{O'rQYO,59mO%eQQO,59mO'yQYO1G/XO(QQQO1G/XO(YQ[O1G.jO(nQ[O1G.lO)SQ[O1G.nOOQW1G.p1G.pOOQW1G.}1G.}O)hQYO'#CnOOQW1G.r1G.rO)|QQO1G.rO*RQ[O1G.hO*gQYO,59OOOQW1G/[1G/[OOQW-E6z-E6zOOQO,59i,59iOOQO-E6{-E6{O*{QYO7+$sO#|QYO'#C{O+SQQO,59YOOQW7+$^7+$^OOQW7+$S7+$SO+[QSO7+$SO+aQYO1G.jO+uQYO1G.lO,ZQYO1G.nPVQYO'#CzO,oQYO,59gOOQO-E6y-E6yOOQW<<Gn<<GnO#|QYO'#CdO#|QYO,59OO#|QYO,59QO#|QYO,59S",
  stateData: "-`~OtOS~ORTOXROaXOfUOhVOiVOjYOlZOvPO~ORbOXROaXOfUOhVOiVO~OXcOZdO]eOjiOyfO{hO~OajOXxXZxX]xXjxXyxX{xX~OVkO~P!nOPlOQmOXdXZdX]dXydX~OjdX{dX~P#^ORoOX!eOaXOfpOhVOiVO~O{qO~ORTOXROaXOfUOhVOiVOjYOlZO~OrTXvTX~P$gOvPOruX~OvPOrua~OZdO]eOyfOXWajWa{Wa~OP{O~O{|O~Oc!OO~P#|OX!fOZ!gO]!hOc!SOyfO~OajOXxXZxX]xXcxXyxXzxX~OcdXzdX~P#^OrTavTa~P$gOrua~PVOrui~PVOvPOrui~OZdO]eOyfOXWijWi{Wi~O]eOXYiZYijYiyYi{Yi~O]eOX[iZ[ij[iy[i{[i~OX!fOZ!gO]!hOyfOz!XOcbX~Oc!ZO~OXcOZdO]eOj!]OyfO{![O~OZ!gO]!hOyfOXWacWazWa~Oruq~PVOz!XOcba~O{!dO~OZ!gO]!hOyfOXWicWizWi~O]!hOXYiZYicYiyYizYi~O]!hOX[iZ[ic[iy[iz[i~OX!fOZ!gO]!hOyfOcoazoa~OiXfvjltZ]Z~",
  goto: "%yyPPPPPz!WP!bP!bP!bP!b!x!bP#TP!b#WP#WPPP!WP!W#n$S$Y$`PPP$jP$m$yQ^OQ`QX!Utv!W!aaZOQ[stv!W!ayWOQRX[cdejkstv!W!X!a!e!f!g!hcgSanx}!Q!R!^!bR!PjyVOQRX[cdejkstv!W!X!a!e!f!g!hQQOY_Qtv!W!aQt^Sv`uR!WwQ!Y}R!c!YQs[R!TsQu^Qw`T!VuwR]O[[OQtv!W!aTr[s`SOQ[stv!W!aQaRQnXQxcQydQzeQ}jQ!QkQ!R!eQ!^!fQ!_!gQ!`!hR!b!X",
  nodeNames: "⚠ Unit PercentSuffix Identifier CalcDoc StatementGroup Binding EqualSign AddExpression PlusBinaryOp MulExpression TimesBinaryOp ExpExpression PowBinaryOp ConvertExpression ConvertOp FunctionCall Opr ArgList Cpr Literal NumberWithUnit Number PercentLiteral String Date Comment NoBinding Heading CommentLine",
  maxTerm: 43,
  nodeProps: [
    ["closedBy", 17,"Cpr"],
    ["openedBy", 19,"Opr"]
  ],
  propSources: [calculusLangHighlight],
  skippedNodes: [0],
  repeatNodeCount: 4,
  tokenData: "*Y~RcXY!^YZ!i]^!ipq!^rs!pst#_uv#vxy#{yz$Qz{#v{|$V|}$[}!O$V!P!Q$a!Q![%Q![!])y!_!`)y#Q#R*O~~*T~!cQt~XY!^pq!^R!pO{QvP~!sTOr!prs#Ss;'S!p;'S;=`#X<%lO!p~#XOh~~#[P;=`<%l!p~#dSl~OY#_Z;'S#_;'S;=`#p<%lO#_~#sP;=`<%l#_~#{OZ~~$QOa~~$VOc~~$[OX~~$aOz~~$fPZ~!P!Q$i~$nSj~OY$iZ;'S$i;'S;=`$z<%lO$i~$}P;=`<%l$i~%VVf~pq%l|}%l!O!P&^!Q!['^!g!h&r#R#S%l#X#Y&r~%oP!Q![%r~%wVf~pq%l|}%l!O!P&^!Q![%r!g!h&r#R#S%l#X#Y&r~&aP!Q![&d~&iRf~!Q![&d!g!h&r#X#Y&r~&uR{|'O}!O'O!Q!['U~'RP!Q!['U~'ZPf~!Q!['U~'cWf~pq%l|}%l}!O'{!O!P&^!Q![(p!g!h&r#R#S%l#X#Y&r~(OP!Q![(R~(UP!Q![(X~([P}!O(_~(bP!Q![(e~(hP!Q![(k~(pOi~~(uVf~pq%l|}%l!O!P&^!Q![)[!g!h&r#R#S%l#X#Y&r~)aWf~pq%l|}%l}!O'{!O!P&^!Q![%r!g!h&r#R#S%l#X#Y&r~*OOV~~*TO]~Q*YO{Q",
  tokenizers: [numberWithUnitTokens, 0, 1, identifierTokens],
  topRules: {"CalcDoc":[0,4]},
  specialized: [{term: 3, get: (value) => spec_Identifier[value] || -1}],
  tokenPrec: 557
})
