// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
import {numberWithUnitTokens} from "./calculus-number-with-unit-tokens.ts"
import {calculusLangHighlight} from "./calculus-lang-highlighting"
export const parser = LRParser.deserialize({
  version: 14,
  states: "'hOqQQOOOxQQO'#CbO!^QSO'#CsO#TQSO'#C|O#mQTO'#CnOOQO'#Cn'#CnOOQO'#C|'#C|O#tQQO'#C|OOQO'#C{'#C{OOQO'#Cu'#CuO$YQQO'#CzQOQQOOO$aQSO,58|O!oQSO'#C|OxQQO,58|OxQQO,59OOxQQO,59QOOQP'#Ci'#CiO$rQRO,59SOOQO,59_,59_O$wQQO,59UOxQQO,58yOOQO,59Z,59ZO%OQQO,59hO%aQQO'#C|O%xQRO'#CnOOQO-E6s-E6sO&SQSO1G.hO&eQSO1G.jO&vQSO1G.lOOQO1G.n1G.nO'XQQO'#ClOOQO1G.p1G.pO'mQQO1G.pO'rQSO1G.eO(TQQO,58|OOQO1G/S1G/SO#tQQO'#CvO(iQQO,59WOOQO7+$[7+$[OOQO7+$P7+$PO(qQQO1G.hO)VQQO1G.jO)kQQO1G.lO*PQQO,59bOOQO-E6t-E6tO#tQQO'#CbO#tQQO,58|O#tQQO,59OO#tQQO,59Q",
  stateData: "*q~OmOS~OSROVPO_VOdSOeTOfTOhWOtXO~OknP~PVOS]OVPO_VOdSOeTOfTO~OV^OX_OZ`OqaOscO~O_dOVpXXpXZpXqpXspX~OTeO~P!oOPfOVbXXbXZbXqbX~OsbX~P#[OShOV!OO_VOdiOeTOfTO~OknX~PVOX_OZ`OVUaqUasUa~OPnO~OapO~P#tOV!POX!QOZ!ROatOqaO~O_dOVpXXpXZpXapXqpXrpX~OabXrbX~P#[OX_OZ`OVUiqUisUi~OZ`OVWiXWiqWisWi~OZ`OVYiXYiqYisYi~OV!POX!QOZ!ROqaOruOa`X~OawO~OV^OX_OZ`OqaOsxO~OX!QOZ!ROVUaaUaqUarUa~OruOa`a~OX!QOZ!ROVUiaUiqUirUi~OZ!ROVWiXWiaWiqWirWi~OZ!ROVYiXYiaYiqYirYi~OV!POX!QOZ!ROqaOajarja~OfqVdhStmXZX~",
  goto: "$PqPPPrPPvPvPvPv!WvP!_Pv!bPPPrP!r!xPPP#O#R#VTWOYmUOPVY^_`deu!O!P!Q!RZbQgor|RqdmTOPVY^_`deu!O!P!Q!RQYORjYQvoR}vRZOTXOYSQOYQ[PQgVQk^Ql_Qm`QodQreQs!OQy!PQz!QQ{!RR|u",
  nodeNames: "⚠ Unit CalcDoc Binding Identifier EqualSign AddExpression PlusBinaryOp MulExpression TimesBinaryOp ExpExpression PowBinaryOp ConvertExpression ConvertOp FunctionCall Opr ArgList Cpr Literal NumberWithUnit Number String Date NoBinding Comment",
  maxTerm: 36,
  propSources: [calculusLangHighlight],
  skippedNodes: [0],
  repeatNodeCount: 2,
  tokenData: ".j~RkXY!vYZ#R]^#Rpq!vrs#Yuv#wxy#|yz$Rz{#w{|$W|}$]}!O$W!P!Q$b!Q![%R!_!`*y!c!k&w!k!l+O!l!}&w#Q#R,Q#R#S&w#T#U,V#U#]&w#]#^,q#^#h&w#h#i-y#i#o&w~~.e~!{Qm~XY!vpq!vR#YOsQtP~#]TOr#Yrs#ls;'S#Y;'S;=`#q<%lO#Y~#qOe~~#tP;=`<%l#Y~#|OX~~$RO_~~$WOa~~$]OV~~$bOr~~$gPX~!P!Q$j~$oSh~OY$jZ;'S$j;'S;=`${<%lO$j~%OP;=`<%l$j~%YUd~S~pq%l!O!P&c!Q!['v!c!}&w#R#S&w#T#o&w~%oP!Q![%r~%wRd~pq%l!O!P&Q!Q![%r~&TP!Q![&W~&]Qd~pq&Q!Q![&W~&hTS~!O!P&w!Q![']!c!}&w#R#S&w#T#o&w~&|TS~!O!P&w!Q![&w!c!}&w#R#S&w#T#o&w~'dUd~S~pq&Q!O!P&w!Q![']!c!}&w#R#S&w#T#o&w~'}Vd~S~pq%l}!O(d!O!P&c!Q![)X!c!}&w#R#S&w#T#o&w~(gP!Q![(j~(mP!Q![(p~(sP}!O(v~(yP!Q![(|~)PP!Q![)S~)XOf~~)`Ud~S~pq%l!O!P&c!Q![)r!c!}&w#R#S&w#T#o&w~)yVd~S~pq%l}!O(d!O!P&c!Q![*`!c!}&w#R#S&w#T#o&w~*gUd~S~pq%l!O!P&c!Q![*`!c!}&w#R#S&w#T#o&w~+OOT~~+TVS~!O!P&w!Q![&w!c!p&w!p!q+j!q!}&w#R#S&w#T#o&w~+qTq~S~!O!P&w!Q![&w!c!}&w#R#S&w#T#o&w~,VOZ~~,[VS~!O!P&w!Q![&w!c!}&w#R#S&w#T#g&w#g#h+j#h#o&w~,vVS~!O!P&w!Q![&w!c!}&w#R#S&w#T#b&w#b#c-]#c#o&w~-dVq~S~!O!P&w!Q![&w!c!}&w#R#S&w#T#h&w#h#i-y#i#o&w~.OVS~!O!P&w!Q![&w!c!}&w#R#S&w#T#c&w#c#d+j#d#o&wQ.jOsQ",
  tokenizers: [numberWithUnitTokens, 0, 1],
  topRules: {"CalcDoc":[0,2]},
  tokenPrec: 435
})
