// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
import {numberWithUnitTokens} from "./calculus-number-with-unit-tokens.ts"
import {calculusLangHighlight} from "./calculus-lang-highlighting"
export const parser = LRParser.deserialize({
  version: 14,
  states: "&xOqQQOOOxQQO'#CaO!^QSO'#CnO!}QSO'#CxO#UQTO'#CiOOQO'#Ci'#CiOOQO'#Cx'#CxO#gQQO'#CxOOQO'#Cv'#CvOOQO'#Cp'#CpO#{QQO'#CuQOQQOOO$SQSO,58{O!lQSO'#CxOxQQO,58{OxQQO,58}OOQP'#Cf'#CfO$bQRO,59POOQO,59Y,59YO$gQQO,59ROxQQO,58yOOQO,59U,59UO$nQQO,59dO$|QQO'#CxO%bQRO'#CiOOQO-E6n-E6nO%vQSO1G.gOOQO1G.i1G.iOOQO1G.k1G.kO&UQQO'#ChOOQO1G.m1G.mO&gQQO1G.mO&lQSO1G.eO&zQQO,58{OOQO1G/O1G/OO#gQQO'#CqO']QQO,59SOOQO7+$X7+$XOOQO7+$P7+$PO'eQQO1G.gO'vQQO,59]OOQO-E6o-E6oO#gQQO'#CaO#gQQO,58{O#gQQO,58}",
  stateData: "(d~OhOS~OSROUPO_SO`TOaTOcWOnVOrXO~OfiP~PVOS]OUPO_SO`TOaTOnVO~OU^OW_Om`OqbO~OncOUlXWlXmlXqlX~OkdO~P!lOPeOU]XW]Xm]Xq]X~OSgOUzO_hO`TOaTOnVO~OfiX~PVOW_OUTamTaqTa~OPlO~OpnO~P#gOU{OW|Om`OprO~OncOUlXWlXmlXplXolX~OPeOU]XW]Xm]Xp]Xo]X~OW_OUTimTiqTi~OU{OW|Om`OosOp[X~OpuO~OU^OW_Om`OqvO~OW|OUTamTapTaoTa~OosOp[a~OW|OUTimTipTioTi~OU{OW|Om`Ooeapea~OamU_SrhcWc~",
  goto: "#omPPPnPrPrPr!Qr!Xr![PPPnP!j!pPPP!v!yP!}TWOYiUOPVY^_cdsz{|ZaQfmpxRociTOPVY^_cdsz{|QYORiYQtmRytRZOTXOYSQOYQ[PQfVQj^Sk_|QmcQpdQqzQw{Rxs",
  nodeNames: "⚠ Unit CalcDoc Binding Identifier AddExpression PlusBinaryOp MulExpression TimesBinaryOp ConvertExpression ConvertOp FunctionCall ArgList Literal NumberWithUnit Number String Date NoBinding Comment",
  maxTerm: 34,
  propSources: [calculusLangHighlight],
  skippedNodes: [0],
  repeatNodeCount: 2,
  tokenData: ".e~RkXY!vYZ#R]^#Rpq!vrs#Yuv#wxy#|yz$Rz{#w{|$W|}$]}!O$W!P!Q$b!Q![%R!_!`*y!c!k&w!k!l+O!l!}&w#Q#R#w#R#S&w#T#U,Q#U#]&w#]#^,l#^#h&w#h#i-t#i#o&w~~.`~!{Qh~XY!vpq!vR#YOqQrP~#]TOr#Yrs#ls;'S#Y;'S;=`#q<%lO#Y~#qO`~~#tP;=`<%l#Y~#|OW~~$ROn~~$WOp~~$]OU~~$bOo~~$gPW~!P!Q$j~$oSc~OY$jZ;'S$j;'S;=`${<%lO$j~%OP;=`<%l$j~%YU_~S~pq%l!O!P&c!Q!['v!c!}&w#R#S&w#T#o&w~%oP!Q![%r~%wR_~pq%l!O!P&Q!Q![%r~&TP!Q![&W~&]Q_~pq&Q!Q![&W~&hTS~!O!P&w!Q![']!c!}&w#R#S&w#T#o&w~&|TS~!O!P&w!Q![&w!c!}&w#R#S&w#T#o&w~'dU_~S~pq&Q!O!P&w!Q![']!c!}&w#R#S&w#T#o&w~'}V_~S~pq%l}!O(d!O!P&c!Q![)X!c!}&w#R#S&w#T#o&w~(gP!Q![(j~(mP!Q![(p~(sP}!O(v~(yP!Q![(|~)PP!Q![)S~)XOa~~)`U_~S~pq%l!O!P&c!Q![)r!c!}&w#R#S&w#T#o&w~)yV_~S~pq%l}!O(d!O!P&c!Q![*`!c!}&w#R#S&w#T#o&w~*gU_~S~pq%l!O!P&c!Q![*`!c!}&w#R#S&w#T#o&w~+OOk~~+TVS~!O!P&w!Q![&w!c!p&w!p!q+j!q!}&w#R#S&w#T#o&w~+qTm~S~!O!P&w!Q![&w!c!}&w#R#S&w#T#o&w~,VVS~!O!P&w!Q![&w!c!}&w#R#S&w#T#g&w#g#h+j#h#o&w~,qVS~!O!P&w!Q![&w!c!}&w#R#S&w#T#b&w#b#c-W#c#o&w~-_Vm~S~!O!P&w!Q![&w!c!}&w#R#S&w#T#h&w#h#i-t#i#o&w~-yVS~!O!P&w!Q![&w!c!}&w#R#S&w#T#c&w#c#d+j#d#o&wQ.eOqQ",
  tokenizers: [numberWithUnitTokens, 0, 1],
  topRules: {"CalcDoc":[0,2]},
  tokenPrec: 331
})
