// @ts-nocheck
// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
import {numberWithUnitTokens} from "./compio-number-with-unit-tokens.ts"
import {identifierTokens} from "./compio-identifier-tokens.ts"
import {compioLangHighlight} from "./compio-lang-highlighting"
const spec_Identifier = {__proto__:null,IN:84, in:84, into:84, as:84, to:84}
export const parser = LRParser.deserialize({
  version: 14,
  states: "*[OVQYOOOOQW'#C{'#C{OVQYO'#DSOtQYO'#CeO!YQ[O'#CxO#VQ[O'#DVO#uQ]O'#CqOOQW'#Cq'#CqOOQW'#DV'#DVO$PQYO'#DVO$eQSO'#CzOOQW'#DU'#DUO%UQYO'#CaQOQQOOO%`QQO'#DSOOQW-E6y-E6yO%hQQO,59nO%pQ[O,59PO!nQ[O'#DVOtQYO,59POtQYO,59ROtQYO,59TOOQP'#Cl'#ClO&UQRO,59VOOQW,59d,59dO&ZQSO,59dO&`QYO,59XOtQYO,58|OOQW,59^,59^OOQW,59`,59`O&gQYO,59qO&xQYO'#DVO'aQZO'#CqOOQW,59f,59fOOQW'#C}'#C}O'kQYO,58{O'uQYO,59nO%hQQO,59nO'|QYO1G/YO(TQQO1G/YO(]Q[O1G.kO(qQ[O1G.mO)VQ[O1G.oOOQW1G.q1G.qOOQW1G/O1G/OO)kQYO'#CoOOQW1G.s1G.sO*PQQO1G.sO*UQ[O1G.hO*jQYO,59POOQW1G/]1G/]OOQW-E6{-E6{OOQO,59j,59jOOQO-E6|-E6|O+OQYO7+$tO$PQYO'#C|O+VQQO,59ZOOQW7+$_7+$_OOQW7+$S7+$SO+_QSO7+$SO+dQYO1G.kO+xQYO1G.mO,^QYO1G.oPVQYO'#C{O,rQYO,59hOOQO-E6z-E6zOOQW<<Gn<<GnO$PQYO'#CeO$PQYO,59PO$PQYO,59RO$PQYO,59T",
  stateData: "-c~OuOS~ORTOYRObXOgUOiVOjVOkYOmZOwPO~ORbOYRObXOgUOiVOjVO~OYcO[dO^eOkiOzfO|hO~ObjOYyX[yX^yXkyXzyX|yX~OVkOWkO~P!nOPlOQmOYeX[eX^eXzeX~OkeX|eX~P#aORoOY!eObXOgpOiVOjVO~O|qO~ORTOYRObXOgUOiVOjVOkYOmZO~OsTXwTX~P$jOwPOsvX~OwPOsva~O[dO^eOzfOYXakXa|Xa~OP{O~O||O~Od!OO~P$POY!fO[!gO^!hOd!SOzfO~ObjOYyX[yX^yXdyXzyX{yX~OdeX{eX~P#aOsTawTa~P$jOsva~PVOsvi~PVOwPOsvi~O[dO^eOzfOYXikXi|Xi~O^eOYZi[ZikZizZi|Zi~O^eOY]i[]ik]iz]i|]i~OY!fO[!gO^!hOzfO{!XOdcX~Od!ZO~OYcO[dO^eOk!]OzfO|![O~O[!gO^!hOzfOYXadXa{Xa~Osvq~PVO{!XOdca~O|!dO~O[!gO^!hOzfOYXidXi{Xi~O^!hOYZi[ZidZizZi{Zi~O^!hOY]i[]id]iz]i{]i~OY!fO[!gO^!hOzfOdpa{pa~OjYgwkmu[^[~",
  goto: "%zzPPPPP{!XPP!cP!cP!cP!c!y!cP#UP!c#XP#XPPP!XP!X#o$T$Z$aPPP$kP$n$zQ^OQ`QX!Utv!W!aaZOQ[stv!W!ayWOQRX[cdejkstv!W!X!a!e!f!g!hcgSanx}!Q!R!^!bR!PjyVOQRX[cdejkstv!W!X!a!e!f!g!hQQOY_Qtv!W!aQt^Sv`uR!WwQ!Y}R!c!YQs[R!TsQu^Qw`T!VuwR]O[[OQtv!W!aTr[s`SOQ[stv!W!aQaRQnXQxcQydQzeQ}jQ!QkQ!R!eQ!^!fQ!_!gQ!`!hR!b!X",
  nodeNames: "⚠ Unit PercentSuffix Identifier CalcDoc StatementGroup Binding EqualSign ColonSign AddExpression PlusBinaryOp MulExpression TimesBinaryOp ExpExpression PowBinaryOp ConvertExpression ConvertOp FunctionCall Opr ArgList Cpr Literal NumberWithUnit Number PercentLiteral String Date Comment NoBinding Heading CommentLine",
  maxTerm: 44,
  nodeProps: [
    ["closedBy", 18,"Cpr"],
    ["openedBy", 20,"Opr"]
  ],
  propSources: [compioLangHighlight],
  skippedNodes: [0],
  repeatNodeCount: 4,
  tokenData: "*_~RcXY!^YZ!i]^!ipq!^rs!pst#_uv#vxy#{yz$Qz{#v{|$V|}$[}!O$V!P!Q$a!Q![%Q![!])y!_!`*O#Q#R*T~~*Y~!cQu~XY!^pq!^R!pO|QwP~!sTOr!prs#Ss;'S!p;'S;=`#X<%lO!p~#XOi~~#[P;=`<%l!p~#dSm~OY#_Z;'S#_;'S;=`#p<%lO#_~#sP;=`<%l#_~#{O[~~$QOb~~$VOd~~$[OY~~$aO{~~$fP[~!P!Q$i~$nSk~OY$iZ;'S$i;'S;=`$z<%lO$i~$}P;=`<%l$i~%VVg~pq%l|}%l!O!P&^!Q!['^!g!h&r#R#S%l#X#Y&r~%oP!Q![%r~%wVg~pq%l|}%l!O!P&^!Q![%r!g!h&r#R#S%l#X#Y&r~&aP!Q![&d~&iRg~!Q![&d!g!h&r#X#Y&r~&uR{|'O}!O'O!Q!['U~'RP!Q!['U~'ZPg~!Q!['U~'cWg~pq%l|}%l}!O'{!O!P&^!Q![(p!g!h&r#R#S%l#X#Y&r~(OP!Q![(R~(UP!Q![(X~([P}!O(_~(bP!Q![(e~(hP!Q![(k~(pOj~~(uVg~pq%l|}%l!O!P&^!Q![)[!g!h&r#R#S%l#X#Y&r~)aWg~pq%l|}%l}!O'{!O!P&^!Q![%r!g!h&r#R#S%l#X#Y&r~*OOW~~*TOV~~*YO^~Q*_O|Q",
  tokenizers: [numberWithUnitTokens, 0, 1, identifierTokens],
  topRules: {"CalcDoc":[0,4]},
  specialized: [{term: 3, get: (value) => spec_Identifier[value] || -1}],
  tokenPrec: 560
})
