// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
export const parser = LRParser.deserialize({
  version: 14,
  states: "%pOVQPOOOqQPO'#C`O!YQPO'#CoO#PQPO'#CxOOQO'#Cj'#CjOOQO'#Cx'#CxOqQPO'#CxOOQO'#Cv'#CvOOQO'#Cq'#CqQVQPOOO#WQPO,58zO#oQPO'#CxOqQPO,58zOqQPO,58|OqQPO,59OOOQO,59Z,59ZO#yQQO,59QO$OQPO,59SOqQPO,58xO$VQPO,59dOOQO-E6o-E6oO$hQPO1G.fO%PQPO1G.hO%hQPO1G.jOOQO1G.l1G.lO&PQPO'#CiOOQO1G.n1G.nO&eQPO1G.nO&jQPO1G.dOOQO1G/O1G/OOqQPO'#CrO&{QPO,59TOOQO7+$Y7+$YOOQO7+$O7+$OO'TQPO,59^OOQO-E6p-E6p",
  stateData: "'v~OiOS~ORROTPO_SO`SOaSObSOdVOnUO~ORZOTPO_SO`SOaSObSOnUO~OT[OV]OX^Om`Oq_O~OnaOTlXVlXXlXmlXqlX~OkbO~P!kOV]OX^OTSamSaqSapSaoSa~OplXolX~P!kOZhO~OpjO~PqOT[OV]OX^Om`OpmO~OV]OX^OTSimSiqSipSioSi~OX^OTUiVUimUiqUipUioUi~OX^OTWiVWimWiqWipWioWi~OT[OV]OX^Om`OonOp]X~OppO~OT[OV]OX^Om`OqqO~OonOp]a~OT[OV]OX^Om`Oofapfa~Obm_T`RqidVXd~",
  goto: "#PmPPnPrPrPrPrPr!OrPPPPnP!R!XPPP!_P!cTVOXeTOPUX[]^abnRkaQXORdXQoiRsoTWOXSQOXQYPQcUQe[Qf]Qg^QiaQlbRrn",
  nodeNames: "⚠ CalcDoc Binding Identifier AddExpression PlusBinaryOp MulExpression TimesBinaryOp ExpExpression PowBinaryOp ConvertExpression Unit FunctionCall ArgList Literal NumberWithUnit Number String Date NoBinding Comment",
  maxTerm: 33,
  skippedNodes: [0],
  repeatNodeCount: 2,
  tokenData: "4S~RuXY#fYZ$ZZ^#fpq#frs%Quv%oxy%tyz%yz{%o{|&O|}&T}!O&O!P!Q&Y!Q![&y!_!`.u!c!k(g!k!l.z!l!w(g!w!x/|!x!}(g#Q#R1j#R#S(g#T#U1o#U#](g#]#^2Z#^#h(g#h#i3c#i#o(g#y#z#f$f$g#f#BY#BZ#f$IS$I_#f$I|$JO#f$JT$JU#f$KV$KW#f&FU&FV#f~~3}~#kYi~X^#fpq#f#y#z#f$f$g#f#BY#BZ#f$IS$I_#f$I|$JO#f$JT$JU#f$KV$KW#f&FU&FV#f~$bYq~i~X^#fpq#f#y#z#f$f$g#f#BY#BZ#f$IS$I_#f$I|$JO#f$JT$JU#f$KV$KW#f&FU&FV#f~%TTOr%Qrs%ds;'S%Q;'S;=`%i<%lO%Q~%iOa~~%lP;=`<%l%Q~%tOV~~%yOn~~&OOp~~&TOT~~&YOo~~&_PV~!P!Q&b~&gSd~OY&bZ;'S&b;'S;=`&s<%lO&b~&vP;=`<%l&b~'QW`~RPpq'j!O!P(R!Q![+Y!c!w(g!w!x)l!x!}(g#R#S(g#T#o(g~'mP!w!x'p~'sP!u!v'v~'yP!f!g'|~(RO_~~(WTRP!O!P(g!Q![({!c!}(g#R#S(g#T#o(gP(lTRP!O!P(g!Q![(g!c!}(g#R#S(g#T#o(g~)SW`~RPpq'j!O!P(g!Q![({!c!w(g!w!x)l!x!}(g#R#S(g#T#o(g~)qVRP!O!P(g!Q![(g!c!u(g!u!v*W!v!}(g#R#S(g#T#o(g~*]VRP!O!P(g!Q![(g!c!f(g!f!g*r!g!}(g#R#S(g#T#o(g~*yT_~RP!O!P(g!Q![(g!c!}(g#R#S(g#T#o(g~+aX`~RPpq'j}!O+|!O!P(R!Q![,q!c!w(g!w!x)l!x!}(g#R#S(g#T#o(g~,PP!Q![,S~,VP!Q![,Y~,]P}!O,`~,cP!Q![,f~,iP!Q![,l~,qOb~~,xW`~RPpq'j!O!P(R!Q![-b!c!w(g!w!x)l!x!}(g#R#S(g#T#o(g~-iX`~RPpq'j}!O+|!O!P(R!Q![.U!c!w(g!w!x)l!x!}(g#R#S(g#T#o(g~.]W`~RPpq'j!O!P(R!Q![.U!c!w(g!w!x)l!x!}(g#R#S(g#T#o(g~.zOk~~/PVRP!O!P(g!Q![(g!c!p(g!p!q/f!q!}(g#R#S(g#T#o(g~/mTm~RP!O!P(g!Q![(g!c!}(g#R#S(g#T#o(gR0RVRP!O!P(g!Q![(g!c!u(g!u!v0h!v!}(g#R#S(g#T#o(gR0mVRP!O!P(g!Q![(g!c!f(g!f!g1S!g!}(g#R#S(g#T#o(gR1ZTZQRP!O!P(g!Q![(g!c!}(g#R#S(g#T#o(g~1oOX~~1tVRP!O!P(g!Q![(g!c!}(g#R#S(g#T#g(g#g#h/f#h#o(g~2`VRP!O!P(g!Q![(g!c!}(g#R#S(g#T#b(g#b#c2u#c#o(g~2|Vm~RP!O!P(g!Q![(g!c!}(g#R#S(g#T#h(g#h#i3c#i#o(g~3hVRP!O!P(g!Q![(g!c!}(g#R#S(g#T#c(g#c#d/f#d#o(g~4SOq~",
  tokenizers: [0, 1],
  topRules: {"CalcDoc":[0,1]},
  tokenPrec: 301
})
