// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
export const parser = LRParser.deserialize({
  version: 14,
  states: "$[OVQPOOOqQPO'#C`O!kQPO'#CiOOQO'#Ce'#CeOOQO'#Cq'#CqOqQPO'#CqO!rQPO'#C^OOQO'#Co'#CoOOQO'#Ck'#CkQVQPOOO!wQPO,58zOqQPO,58zOqQPO,58{OOQO'#Cc'#CcOqQPO,58|OOQO,59T,59TO#cQPO,59]OqQPO,58xOOQO-E6i-E6iO#jQPO1G.fOOQO1G.g1G.gO$UQPO1G.hOOQO1G.w1G.wO$cQPO1G.dOOQO7+$O7+$O",
  stateData: "$u~ObOS~ORUOYROZRO[RO^VOfPOgPOkTO~OYROZRO[ROfPOgPOkTO~OW]OfZOgZOh[Oi[Oj[O~Om_O~P!VOdaO~Oh[Oi[Oj[OWSafSagSamSalSa~OlfO~P!VOh[Oi[Oj[OWSifSigSimSilSi~OWUimUilUi~P!YOmhO~P!VO[WgYRmb^i^~",
  goto: "!lfPPgPkkkuPkPPPgPzPPP!QP!UTVOXaSOPTXZ[^aV^Q`gQXORbXTWOXSQOXQYPQ`TQcZQd[Qe^Rga",
  nodeNames: "⚠ CalcDoc Binding Identifier AddExpression MulExpression ConvertExpression ConvertOp IN Literal Number String Date NoBinding Comment",
  maxTerm: 29,
  skippedNodes: [0],
  repeatNodeCount: 1,
  tokenData: ",S~RnXY#PYZ#tZ^#Ppq#Prs$kuv%Yxy%_yz%dz{%i{|%n}!O%s!P!Q%x!Q![&i!_!`*[!c!k'P!k!l*a!l!}'P#R#S'P#T#]'P#]#^+c#^#o'P#y#z#P$f$g#P#BY#BZ#P$IS$I_#P$I|$JO#P$JT$JU#P$KV$KW#P&FU&FV#P~~+}~#UYb~X^#Ppq#P#y#z#P$f$g#P#BY#BZ#P$IS$I_#P$I|$JO#P$JT$JU#P$KV$KW#P&FU&FV#P~#{Ym~b~X^#Ppq#P#y#z#P$f$g#P#BY#BZ#P$IS$I_#P$I|$JO#P$JT$JU#P$KV$KW#P&FU&FV#P~$nTOr$krs$}s;'S$k;'S;=`%S<%lO$k~%SOZ~~%VP;=`<%l$k~%_Oj~~%dOk~~%iOl~~%nOh~~%sOf~~%xOg~~%}Pi~!P!Q&Q~&VS^~OY&QZ;'S&Q;'S;=`&c<%lO&Q~&fP;=`<%l&Q~&pTY~R~!O!P'P!Q!['e!c!}'P#R#S'P#T#o'P~'UTR~!O!P'P!Q!['P!c!}'P#R#S'P#T#o'P~'lUY~R~}!O(O!O!P'P!Q![(s!c!}'P#R#S'P#T#o'P~(RP!Q![(U~(XP!Q![([~(_P}!O(b~(eP!Q![(h~(kP!Q![(n~(sO[~~(zTY~R~!O!P'P!Q![)Z!c!}'P#R#S'P#T#o'P~)bUY~R~}!O(O!O!P'P!Q![)t!c!}'P#R#S'P#T#o'P~){TY~R~!O!P'P!Q![)t!c!}'P#R#S'P#T#o'P~*aOd~~*fVR~!O!P'P!Q!['P!c!p'P!p!q*{!q!}'P#R#S'P#T#o'P~+STW~R~!O!P'P!Q!['P!c!}'P#R#S'P#T#o'P~+hVR~!O!P'P!Q!['P!c!}'P#R#S'P#T#b'P#b#c*{#c#o'P~,SOm~",
  tokenizers: [0],
  topRules: {"CalcDoc":[0,1]},
  tokenPrec: 164
})
