// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  CalcDoc = 1,
  Binding = 2,
  Identifier = 3,
  AddExpression = 4,
  PlusBinaryOp = 5,
  MulExpression = 6,
  TimesBinaryOp = 7,
  ConvertExpression = 8,
  ConvertOp = 9,
  IN = 10,
  Literal = 11,
  Number = 12,
  String = 13,
  Date = 14,
  NoBinding = 15,
  Comment = 16
