// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  CalcDoc = 1,
  Binding = 2,
  Identifier = 3,
  AddExpression = 4,
  MulExpression = 5,
  ConvertExpression = 6,
  ConvertOp = 7,
  IN = 8,
  Literal = 9,
  Number = 10,
  String = 11,
  Date = 12,
  NoBinding = 13,
  Comment = 14
