// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
export const parser = LRParser.deserialize({
  version: 14,
  states: "%jOVQPOOOnQPO'#C`O!SQPO'#CmO!sQPO'#CvOOQO'#Ci'#CiOOQO'#Cv'#CvOnQPO'#CvOOQO'#Ct'#CtOOQO'#Co'#CoQVQPOOO!zQPO,58zO#`QPO'#CvOnQPO,58zOnQPO,58|OOQO'#Ce'#CeOnQPO,59OOOQO,59X,59XO#jQPO,59ROnQPO,58xO#qQPO,59bOOQO-E6m-E6mO$PQPO1G.fOOQO1G.h1G.hO$eQPO1G.jO$yQPO'#ChOOQO1G.m1G.mO%[QPO1G.mO%aQPO1G.dOOQO1G.|1G.|OnQPO'#CpO%oQPO,59SOOQO7+$X7+$XOOQO7+$O7+$OO%wQPO,59[OOQO-E6n-E6n",
  stateData: "&e~OgOS~ORROTPO^SO_SO`SObVOkUO~ORZOTPO^SO_SO`SOkUO~OT[OV]OY^On`O~OkaOTjXVjXYjXnjX~OibO~P!bOV]OTSaYSanSamSalSa~OmjXljX~P!bOmiO~PnOT[OV]OY^OmlO~OV]OTSiYSinSimSilSi~OT[OV]OYWinWimWilWi~OT[OV]OY^OlmOm[X~OmoO~OT[OV]OY^OnpO~OlmOm[a~OT[OV]OY^Oldamda~O`YT^RngbVb~",
  goto: "#UkPPlPpPpPp|Pp!TpPPPlP!W!^PPP!dP!hTVOXeTOPUX[]_abmZ_QchkqRjaQXORdXQnhRrnTWOXSQOXQYPQcUQe[Qf]Qg_QhaQkbRqm",
  nodeNames: "⚠ CalcDoc Binding Identifier AddExpression PlusBinaryOp MulExpression TimesBinaryOp ConvertExpression ConvertOp IN FunctionCall ArgList Literal Number String Date NoBinding Comment",
  maxTerm: 30,
  skippedNodes: [0],
  repeatNodeCount: 2,
  tokenData: "-P~RpXY#VYZ#zZ^#Vpq#Vrs$quv%`xy%eyz%jz{%`{|%o|}%t}!O%o!P!Q%y!Q![&j!_!`+X!c!k'f!k!l+^!l!}'f#Q#R%`#R#S'f#T#]'f#]#^,`#^#o'f#y#z#V$f$g#V#BY#BZ#V$IS$I_#V$I|$JO#V$JT$JU#V$KV$KW#V&FU&FV#V~~,z~#[Yg~X^#Vpq#V#y#z#V$f$g#V#BY#BZ#V$IS$I_#V$I|$JO#V$JT$JU#V$KV$KW#V&FU&FV#V~$RYn~g~X^#Vpq#V#y#z#V$f$g#V#BY#BZ#V$IS$I_#V$I|$JO#V$JT$JU#V$KV$KW#V&FU&FV#V~$tTOr$qrs%Ts;'S$q;'S;=`%Y<%lO$q~%YO_~~%]P;=`<%l$q~%eOV~~%jOk~~%oOm~~%tOT~~%yOl~~&OPV~!P!Q&R~&WSb~OY&RZ;'S&R;'S;=`&d<%lO&R~&gP;=`<%l&R~&qT^~R~!O!P'Q!Q![(b!c!}'f#R#S'f#T#o'f~'VTR~!O!P'f!Q!['z!c!}'f#R#S'f#T#o'f~'kTR~!O!P'f!Q!['f!c!}'f#R#S'f#T#o'f~(RT^~R~!O!P'f!Q!['z!c!}'f#R#S'f#T#o'f~(iU^~R~}!O({!O!P'Q!Q![)p!c!}'f#R#S'f#T#o'f~)OP!Q![)R~)UP!Q![)X~)[P}!O)_~)bP!Q![)e~)hP!Q![)k~)pO`~~)wT^~R~!O!P'Q!Q![*W!c!}'f#R#S'f#T#o'f~*_U^~R~}!O({!O!P'Q!Q![*q!c!}'f#R#S'f#T#o'f~*xT^~R~!O!P'Q!Q![*q!c!}'f#R#S'f#T#o'f~+^Oi~~+cVR~!O!P'f!Q!['f!c!p'f!p!q+x!q!}'f#R#S'f#T#o'f~,PTY~R~!O!P'f!Q!['f!c!}'f#R#S'f#T#o'f~,eVR~!O!P'f!Q!['f!c!}'f#R#S'f#T#b'f#b#c+x#c#o'f~-POn~",
  tokenizers: [0],
  topRules: {"CalcDoc":[0,1]},
  tokenPrec: 240
})
