// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
export const parser = LRParser.deserialize({
  version: 14,
  states: "$[OVQPOOOnQPO'#C`O!SQPO'#CkOOQO'#Cg'#CgOOQO'#Cs'#CsO!bQPO'#CsOnQPO'#CsOOQO'#Cq'#CqOOQO'#Cm'#CmQVQPOOO!sQPO,58zOnQPO,58zOnQPO,58|OOQO'#Ce'#CeOnQPO,59OOOQO,59V,59VOnQPO,58xO#UQPO,59_OOQO-E6k-E6kO#dQPO1G.fOOQO1G.h1G.hO#uQPO1G.jO$WQPO1G.dOOQO1G.y1G.yOOQO7+$O7+$O",
  stateData: "$o~OdOS~ORTOTPO[RO]RO^RO`VOhUO~ORSOTPO[RO]RO^ROhUO~OTZOV[OY]Oj_O~Of`OTgXVgXYgXjgX~OV[OTSaYSajSaiSa~OTZOV[OY]OigO~OV[OTSiYSijSiiSi~OTZOV[OYWijWiiWi~OTZOV[OY]OjhO~O^Y[`VjRd~",
  goto: "!nhPPiPmPmPmwPmPPPiP|PPP!SP!WTVOXaSOPUXZ[^`V^QafQXORbXTWOXSQOXQYPQaUQcZQd[Qe^Rf`",
  nodeNames: "⚠ CalcDoc Binding Identifier AddExpression PlusBinaryOp MulExpression TimesBinaryOp ConvertExpression ConvertOp IN Literal Number String Date NoBinding Comment",
  maxTerm: 26,
  skippedNodes: [0],
  repeatNodeCount: 1,
  tokenData: ",t~RnXY#PYZ#tZ^#Ppq#Prs$kuv%Yxy%_yz%dz{%Y{|%i}!O%i!P!Q%n!Q![&_!_!`*|!c!k'Z!k!l+R!l!}'Z#R#S'Z#T#]'Z#]#^,T#^#o'Z#y#z#P$f$g#P#BY#BZ#P$IS$I_#P$I|$JO#P$JT$JU#P$KV$KW#P&FU&FV#P~~,o~#UYd~X^#Ppq#P#y#z#P$f$g#P#BY#BZ#P$IS$I_#P$I|$JO#P$JT$JU#P$KV$KW#P&FU&FV#P~#{Yj~d~X^#Ppq#P#y#z#P$f$g#P#BY#BZ#P$IS$I_#P$I|$JO#P$JT$JU#P$KV$KW#P&FU&FV#P~$nTOr$krs$}s;'S$k;'S;=`%S<%lO$k~%SO]~~%VP;=`<%l$k~%_OV~~%dOh~~%iOi~~%nOT~~%sPV~!P!Q%v~%{S`~OY%vZ;'S%v;'S;=`&X<%lO%v~&[P;=`<%l%v~&fT[~R~!O!P&u!Q![(V!c!}'Z#R#S'Z#T#o'Z~&zTR~!O!P'Z!Q!['o!c!}'Z#R#S'Z#T#o'Z~'`TR~!O!P'Z!Q!['Z!c!}'Z#R#S'Z#T#o'Z~'vT[~R~!O!P'Z!Q!['o!c!}'Z#R#S'Z#T#o'Z~(^U[~R~}!O(p!O!P&u!Q![)e!c!}'Z#R#S'Z#T#o'Z~(sP!Q![(v~(yP!Q![(|~)PP}!O)S~)VP!Q![)Y~)]P!Q![)`~)eO^~~)lT[~R~!O!P&u!Q![){!c!}'Z#R#S'Z#T#o'Z~*SU[~R~}!O(p!O!P&u!Q![*f!c!}'Z#R#S'Z#T#o'Z~*mT[~R~!O!P&u!Q![*f!c!}'Z#R#S'Z#T#o'Z~+ROf~~+WVR~!O!P'Z!Q!['Z!c!p'Z!p!q+m!q!}'Z#R#S'Z#T#o'Z~+tTY~R~!O!P'Z!Q!['Z!c!}'Z#R#S'Z#T#o'Z~,YVR~!O!P'Z!Q!['Z!c!}'Z#R#S'Z#T#b'Z#b#c+m#c#o'Z~,tOj~",
  tokenizers: [0],
  topRules: {"CalcDoc":[0,1]},
  tokenPrec: 160
})
